name: ziyara_partner
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: '>=3.2.5 <4.0.0'

dependencies:
  firebase_auth: ^4.19.2
  firebase_core: ^2.30.0
  firebase_core_platform_interface: ^5.0.0
  flutter:
    sdk: flutter
  flutter_bloc: ^8.1.5
  form_field_validator: ^1.1.0
  go_router: ^13.2.4
  provider: ^6.1.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

flutter:
  assets:
    - assets/images/

  uses-material-design: true