// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyA9EizM06a5B7NfkLaag_vDRe2S7q5tDnU',
    appId: '1:227118068713:web:b42fa1b6fc1ae4199d5178',
    messagingSenderId: '227118068713',
    projectId: 'ziyara-46a06',
    authDomain: 'ziyara-46a06.firebaseapp.com',
    storageBucket: 'ziyara-46a06.appspot.com',
    measurementId: 'G-FW6RYK9MTT',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBFQ9tNvUZbQ38_pKwndf8BrQaY1QI_7Uw',
    appId: '1:227118068713:android:a99df2bc1b0ef4a19d5178',
    messagingSenderId: '227118068713',
    projectId: 'ziyara-46a06',
    storageBucket: 'ziyara-46a06.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDHOZSZKyiNk6rr574XM1pPjtiV-CYjm58',
    appId: '1:227118068713:ios:0dc88aceefeae6879d5178',
    messagingSenderId: '227118068713',
    projectId: 'ziyara-46a06',
    storageBucket: 'ziyara-46a06.appspot.com',
    iosBundleId: 'com.example.ziyaraPartner',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDHOZSZKyiNk6rr574XM1pPjtiV-CYjm58',
    appId: '1:227118068713:ios:0dc88aceefeae6879d5178',
    messagingSenderId: '227118068713',
    projectId: 'ziyara-46a06',
    storageBucket: 'ziyara-46a06.appspot.com',
    iosBundleId: 'com.example.ziyaraPartner',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyA9EizM06a5B7NfkLaag_vDRe2S7q5tDnU',
    appId: '1:227118068713:web:b7e2ba2dcbee33ae9d5178',
    messagingSenderId: '227118068713',
    projectId: 'ziyara-46a06',
    authDomain: 'ziyara-46a06.firebaseapp.com',
    storageBucket: 'ziyara-46a06.appspot.com',
    measurementId: 'G-N1LWPZ9G07',
  );

}